##.title
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##
## Dart/Flutter (DF) Packages by DevCetra.com & contributors. Use of this
## source code is governed by an an MIT-style license that can be found in the
## LICENSE file located in this project's root directory.
##
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##.title~

name: df_config
description: A package that provides methods to load configuration data and access it at runtime.
version: 0.2.1
repository: https://github.com/robmllze/df_config
funding:
  - https://www.buymeacoffee.com/robmllze
topics:
  - cache
  - json
  - localization
  - parser
  - utils

## -----------------------------------------------------------------------------

environment:
  sdk: ">=3.5.0 <4.0.0"

## -----------------------------------------------------------------------------

dependencies:
  df_collection: ^0.3.0
  df_type: ^0.2.3
  df_string: ^0.2.1
  yaml: ^3.1.2
  meta: ^1.15.0
  equatable: ^2.0.5
  path: ^1.9.0

## -----------------------------------------------------------------------------

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.8
